name: tag

on:
  push:
    branches:
      - "master"

jobs:
  tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14.16.1']
    container: blowltd/docker-ci:node-${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: prepare repository
        run: |
          git checkout master
          git remote set-url origin https://github.com/${GITHUB_REPOSITORY}.git
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@v8.0.18'
        env:
          TOKEN_GITHUB_CI: ${{ secrets.GREN_CI_TOKEN }}
        with:
          tag-prefix:  ''
      - name: github release
        run: gren release --data-source=prs --override -g label
        env:
          GREN_GITHUB_TOKEN: ${{ secrets.GREN_CI_TOKEN }}

